student_app/urls.py
from django.conf.urls import url
from student_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete


# SET THE NAMESPACE!
app_name = 'student_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^index/$',views.index,name='index'),
    url(r'^switch/$',views.switch,name='switch'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^view_tutors/$',views.view_tutors,name='view_tutors'),
   # url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^session_list/(?P<tutor_id>\w+)$', views.session_list, name='session_list'),
    url(r'^index/update_wallet', views.update_wallet, name='update_wallet'),
    url(r'^warning/$', views.warning, name='warning'),
    url(r'^transactions/$', views.transactions, name='transactions'),
    #url(r'^timeSlots/$',views.timeSlots,name='timeslots'),
    url(r'^sort_price/$', views.sort_price, name='sort_price'),
    #url(r'^sort_rating/$', views.sort_rating, name='sort_rating'),
]

tutor_app/urls.py
from django.conf.urls import url
from tutor_app import views

# SET THE NAMESPACE!
app_name = 'tutor_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^index/$',views.index,name='index'),
    url(r'^switch/$',views.switch,name='switch'),
    url(r'^profile/(?P<tutor_id>\w+)/$', views.profile, name='profile'),
    url(r'^edit/', views.edit_profile, name='edit_profile'),
    url(r'^blockSession/$',views.blockSession, name='blockSession'),
    url(r'^timeSlots/$',views.timeSlots, name='timeSlots'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^review/$', views.review_list, name='review_list'),
    url(r'^tutor/$', views.tutor_list, name='tutor_list'),
    url(r'^tutor/(?P<tutor_id>[0-9]+)/$', views.tutor_detail, name='tutor_detail'),
    url(r'^deactivate/$', views.deactivate, name='deactivate'),
    url(r'^tutor/(?P<tutor_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^transactions/$',views.transactions,name='transactions')
]

tutoria/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from start_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^student_app/',include('student_app.urls')),
    url(r'^myTutor_app/',include('myTutor_app.urls')),
    url(r'^tutor_app/',include('tutor_app.urls')),
    url(r'^session_app/',include('session_app.urls')),
    url(r'^reset-password/$',password_reset,name='password_reset'),
    url(r'^reset-password/done/$',password_reset_done,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset-password/complete/$',password_reset_complete,name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutor_app/models.py
from django.db import models
from django.contrib.auth.models import User
from course_app.models import Course, Subject
from datetime import datetime
import numpy as np

# Create your models here.
class Timeslot(models.Model):
    
    date_of_slot = models.DateTimeField(null=True);
    #time_of_slot = models.TimeField(null=True);


class Tutor(models.Model):

    user = models.OneToOneField(User,null=True)
    first_name = models.CharField(max_length=30,null=True);
    last_name = models.CharField(max_length=30,null=True);
    wallet = models.FloatField(null=True)
    phone = models.CharField(max_length=30,null=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    bio = models.TextField(null=True)
    contracted = models.BooleanField(default=False)
    salary = models.FloatField(default=0)
    courses = models.ManyToManyField(Course)
    subject_tag = models.ManyToManyField(Subject)
    
    #CPPS = C and C++
    #CMVS = Computer Vision
    #MATH = Mathematic, Statistic and Algebra
    #AIML = AI and Machine Learning
    #WWNT = World-wide WEB and Networking
    #APPS = Application Development and Java
    #ARVR = Augmented and Virtual Reality
    #SWEG = Software Engineering
    #STDS = System and Design

    university = models.CharField(max_length=30,null=True)
    active = models.BooleanField(default=True)
    #average_rating = models.FloatField(default=2)
    #blocked_timeslots = models.ManyToManyField(Timeslot, null=True)
    def __str__(self):
        return self.user.username
        
    def average_rating(self):
      all_ratings = map(lambda x: x.rating, self.review_set.all())
      return np.mean(all_ratings)
      

        
class Review(models.Model):
    
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
    )
    
    tutor = models.ForeignKey(Tutor)
    user_name = models.CharField(max_length = 100)
    comment = models.CharField(max_length = 200)
    pub_date = models.DateTimeField(default=datetime.now(), blank=True)
    rating = models.IntegerField(choices = RATING_CHOICES)
    
class Transaction_T(models.Model):
    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    amount = models.FloatField(null = True)
    pub_date = models.DateTimeField(null = True)
    desc = models.CharField(max_length=30,null=True)

tutor_app/views.py
from django.shortcuts import render
from tutor_app.forms import UserForm , TutorForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from tutor_app.models import Tutor, Review
from tutor_app.forms import EditProfileForm, EditUserForm, ReviewForm
import datetime
import json
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from session_app.models import Session
from django.shortcuts import get_object_or_404
from tutor_app.models import Transaction_T

# Create your views here.
def index(request):
    
    user_id=request.user
    # student_id=Student.objects.get(user=user_id)p
    # session=Session.objects.filter(student=student_id)
    # print(session)
    try:
        tutor_id=Tutor.objects.get(user=user_id)
        print(tutor_id)
    except:
        tutor_id= None
    if tutor_id != None:    
        try:
            session = Session.objects.filter(tutor=tutor_id,status=1)
            print (session)
            return render(request,'tutor_app/index.html',{'sessions':session})
        except Session.DoesNotExist:
            session = None
            print(session)
    return render(request,'tutor_app/index.html')

def switch(request):
    logout(request)
    return redirect('/student_app/index')
    
def profile(request,tutor_id):
    tutor = Tutor.objects.get(id=tutor_id)
    return render(request,'tutor_app/profile.html',{'tutor':tutor})


@login_required
def user_logout(request):
    logout(request)
    return render(request,'tutor_app/index.html')

def register(request):
    registered =False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        tutor_form = TutorForm(data=request.POST)

        if user_form.is_valid() and tutor_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            tutor = tutor_form.save(commit=False)
            tutor.user = user

            if 'profile_pic' in request.FILES:
                tutor.profile_pic = request.FILES['profile_pic']

            tutor.save()

            registered = True

        else:
            print(user_form.errors,tutor_form.errors)

    else:
        user_form = UserForm()
        tutor_form = TutorForm()

    return render(request,'tutor_app/registration.html',
                            {'user_form':user_form,
                            'tutor_form':tutor_form,
                            'registered':registered}
                            )

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_id =authenticate(username=username,password=password)
        try:
            tutor = Tutor.objects.get(user=user_id)
        except:
            tutor=None
        if user_id:
            if tutor != None:
                login(request,user_id)
                return redirect('/tutor_app/index')

            else:
                return HttpResponse('Not Registered as a Tutor')
        else:
            print('Someone Tried to login and failed')
            print('Username: {} and password: {}'.format(username,password))
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request,'tutor_app/login.html',{})
        
@login_required      
def edit_profile(request):
    args = {}
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user.tutor)
        form2 = EditUserForm(request.POST, instance=request.user)
        #form3 = EditTagForm(request.POST, instance=request.user.tutor)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            #form3.save()
            return redirect('/tutor_app/index')
        else:
            messages.warning(request, "Invalid Form")
            print("not valid form")
            return render(request, 'student_app/warning.html')
    
    else:
        form = EditProfileForm(instance=request.user.tutor)
        form2 = EditUserForm(instance=request.user)
        tutor = Tutor.objects.get(user = request.user)
        #tags = get_object_or_404(tutor, pk=1)
        #form3 = EditTagForm(instance=request.user.tutor)
        args['form'] = form
        args['form2'] = form2
        #args['form3'] = form3
        return render(request, 'tutor_app/edit_profile.html', args)
        
def datetime_range(start, end, delta):
    current = start
    while current < end:
        yield current
        current += delta
            
def timeSlots(request):
    preset_time = []
    time_slot = []
    date_array = []
    block_slot = []
    lock_slot = []
    book_slot = []
    time_range = 18
    elem_time = datetime.time(9, 00)
    time_delta = datetime.timedelta(minutes = 30)
    tutor = Tutor.objects.get(user=request.user)

    if tutor.contracted == False:
        time_range = 9
        time_delta = datetime.timedelta(minutes = 60)
    for i in range(time_range):
        temp_time = datetime.datetime.combine(datetime.date(1, 1, 1), elem_time)
        preset_time.append(elem_time)
        elem_time = (temp_time + time_delta).time()

    curr_date = datetime.datetime.now().date()

    date_delta = datetime.timedelta(days = 1)
    lock_time = datetime.datetime.now() + date_delta + datetime.timedelta(hours = 8)

    for i in range(14):
        temp_date = datetime.datetime.combine(curr_date, datetime.time(1,1))
        date_array.append(curr_date.strftime("%d/%m/%y (%a)"))
        curr_date = (temp_date + date_delta).date()
    for i in range(time_range):
        curr_date = datetime.datetime.now().date()
        time_slot.append(preset_time[i].strftime("%H:%M"))
        for j in range(14):
            time_to_append = datetime.datetime.combine(curr_date, preset_time[i]).isoformat()
            if Session.objects.filter(session_time = time_to_append).filter(tutor = tutor).exists():
                session = Session.objects.filter(session_time = time_to_append).filter(tutor = tutor).get()
                print("session found")
                if session.status == 2:
                    print("and it is blocked")
                    block_slot.append(time_to_append)
                elif session.status == 1:
                    book_slot.append(time_to_append)
            if datetime.datetime.combine(curr_date, preset_time[i]) <= lock_time:
                lock_slot.append(time_to_append)
            time_slot.append(time_to_append)
            temp_date = datetime.datetime.combine(curr_date, datetime.time(1,1))
            curr_date = (temp_date + date_delta).date()

    return render(request,'tutor_app/timeSlots.html',{'timeSlot':time_slot, 'date_array':date_array, 'block_slot':block_slot, 'lock_slot':lock_slot, 'book_slot':book_slot})

def blockSession(request):

    if request.method=='POST':
        user_id=request.user
        json_data=json.loads(request.POST['data'])
        for data in json_data:
            tutor = Tutor.objects.get(user=user_id)
            if Session.objects.filter(session_time = data['timeslot']).filter(tutor = tutor).exists():
                print(data['timeslot']+ " Session Exist")
                session = Session.objects.filter(session_time = data['timeslot']).filter(tutor = tutor).get()
                if data['status'] == 0:
                    print("Block session deleted")
                    session.delete()
            else:
                if data['status'] == 1:
                    print(data['timeslot']+ " Block session Created")
                    session = Session(tutor = tutor, session_time = data['timeslot'], status = 2)
                    session.save()

        messages.success(request, 'Your timeslot has been updated.')
        return  JsonResponse({'message': 'Timeslot Edit Saved'})

    
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was changed successfully')
            return redirect('change_password')
        else:
            messages.error(request, 'ERROR > ')
        
    else: 
        form = PasswordChangeForm(request.user)
    return render(request, 'student_app/change_password.html', {
        'form': form
    })

def review_list(request):
    latest_review_list = Review.objects.order_by('-pub_date')[:9]
    context = {'latest_review_list':latest_review_list}
    return render(request, 'tutor_app/review_list.html', context)
    
def review_detail(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    return render(request, 'tutor_app/review_detail.html', {'review': review})

def tutor_list(request):
    tutor_list = Tutor.objects.order_by('last_name')
    context = {'tutor_list':tutor_list}
    return render(request, 'tutor_app/tutor_list.html',{'tutor_list':tutor_list})
    

    
def tutor_detail(request, tutor_id):
    tutor = get_object_or_404(Tutor, pk=tutor_id)
    return render(request, 'tutor_app/tutor_detail.html', {'tutor':tutor})
    
def deactivate(request):
    tutor = Tutor.objects.get(user=request.user)
    print("changing active status")
    if tutor.active == True:
        tutor.active = False
    else:
        tutor.active = True
    tutor.save()
    return redirect('tutor_app:index')

def add_review(request, tutor_id):
    tutor = get_object_or_404(Tutor, pk=tutor_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        rating = form.cleaned_data['rating']

templates/tutor_app/add_review.html
{% extends "student_app/base.html" %}
{% block body_block %}
<div class = "jumbotron" >
    <br>
    <h3>Add your review</h3>
    <form action="{% url 'tutor_app:add_review' tutor.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Add" />
    </form>    
</div>
{% endblock %}

templates/tutor_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Tutoria (Tutor mode)</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="/static/css/main.css"/>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<style type="text/css">
	body {
		background-color: #f97925;
	}
</style>
  <body><br>
    <nav class="navbar  navbar-default navbar-static-top">
			<div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          {% if user.is_authenticated %}
          <li><a class="navbar-brand" href="{% url 'tutor_app:index' %}">Tutoria</a></li>
          {% else %}
          <li><a class="navbar-brand" href="{% url 'index' %}">Tutoria</a></li>
          {% endif %}
					{% if user.is_authenticated %}
            <li><a href="{% url 'tutor_app:timeSlots' %}">Edit Timeslot</a></li>
          {% endif %}
        </ul>
				<ul class="nav navbar-nav navbar-right">
					{# Some logic on what to display for last item#}
					<li  class="nav-item"><a class="navbar-link" href="{% url 'tutor_app:switch' %}">Switch to Student</a></li>
					{% if user.is_anonymous %}
          <li  class="nav-item"><a class="navbar-link" href="{% url 'tutor_app:register' %}">Register</a></li>
          {% endif %}
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></a>
						<ul class="dropdown-menu">
						    
						    <li><a  class="dropdown-item">Wallet: ${{user.tutor.wallet}}</a></li>
							<li><a class="dropdown-item"  href="{% url 'tutor_app:edit_profile' %}">Edit Profile</a></li>
							<li><a class="dropdown-item"  href="{% url 'tutor_app:transactions' %}">Transaction History</a></li>
							{% if user.is_superuser %}
								<li role="separator" class="divider"></li>
								<li  class="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">Admin Panel</a></li>
							{% endif %}
							{% if user.tutor.active %}
							    <li role="separator" class="divider"></li>
							    <li><a class="dropdown-item" style="color:red;"  href="{% url 'tutor_app:deactivate' %}">Deactivate</a></li>
							{% else %}
							    <li role="separator" class="divider"></li>
							    <li><a class="dropdown-item" style="color:green;"  href="{% url 'tutor_app:deactivate' %}">Activate</a></li>
							{% endif %}
							<li role="separator" class="divider"></li>
							<li><a class="dropdown-item"  href="{% url 'tutor_app:logout' %}">Logout</a></li>
						</ul>
					</li>
					{% else %}
						<li  class="nav-item"><a class="navbar-link" href="{% url 'tutor_app:user_login' %}">Login</a></li>
					{% endif %}
        </ul>
			</div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

templates/tutor_app/edit_profile.html
{% extends "tutor_app/base.html" %}

{% block body_block %}
<div class="container jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form2.as_p }}
        <p style="font-size: 14px; font-weight: bold">Preview Profile Pic:</p>
        <div style="display: flex; align-items: center; justify-content: center; width: 400px; border: 2px dashed lightgray">
            <img id="preview" src="../../media/{{user.tutor.profile_pic}}" alt="your profile pic" style="max-width: 400px;"/>
        </div>
        {{ form.as_p }}
        <a href="{%url 'tutor_app:change_password' %}"  class = "btn">Change Password</a>
        <button type="submit">Submit</button>
    </form>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#preview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#id_profile_pic').change(function(){
            readURL(this);
        });
    });
</script>
{% endblock %}

templates/tutor_app/login.html
{% extends 'tutor_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'tutor_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>
        <a href='/reset-password'>Forgot Password</a>

    </div>
  </div>
{% endblock %}

templates/tutor_app/profile.html
{% extends "student_app/base.html" %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <div style="display: flex; width: 100%;">
            <div class="profile_pic_box" style="background-image: url(../../../media/{{tutor.profile_pic}})"></div>
            <div style="margin-left: 36px; padding-left: 36px;width: 450px; border-left: #FFF dashed 2px">
                <h4>Name</h4>
                <p>{{tutor.first_name}} {{tutor.last_name}}</p>
                <h4>E-mail Address</h4>
                <p>{{tutor.user.email}}</p>
                <h4>Contact number</h4>
                <p>{{tutor.phone}}</p>
                <h4>Biography</h4>
                <p>{{tutor.bio}}</p>
                {% if tutor.contracted %}
                    <h4>Contracted tutor</h4>
                {% else %}
                    <h4>Fees per hour:</h4><p>{{tutor.salary}}</p>
                {% endif %}
            </div>
            <div class="flex flex-column flex-center rating-box">
                <div style="font-size:20px;font-weight:500;">Rating:</div>
                {% if tutor.review_set.count == 0 %}
                <div><span class="stars">0</span></div>
                {% else %}
                <div><span class="stars">{{tutor.average_rating|floatformat}}</span></div>
                {% endif %}
                <div style="color:#878787;">{{ tutor.average_rating | floatformat }}</div>
                <div><a href={% url 'tutor_app:tutor_detail' tutor_id=tutor.id %}>{{tutor.review_set.count}} review(s)</a></div>
            </div>
        </div>
        
    </div>
    <a type="button" class="btn btn-primary" href={% url 'student_app:session_list' tutor_id=tutor.id %}>Book Session</a>
    
</div>
<script type="text/javascript">
    $.fn.stars = function() {
      return $(this).each(function() {
        // Get the value
        var val = parseFloat($(this).html());
        // Make sure that the value is in 0 - 5 range, multiply to get width
        var size = Math.max(0, (Math.min(6, val))) * 16;
        // Create stars holder
        var $span = $('<span />').width(size);
        // Replace the numerical value with stars
        $(this).html($span);
      });
    }
    $(document).ready(function() {
      $('span.stars').stars();
    });
  </script>



{% endblock %}

templates/tutor_app/registration.html
{% extends "tutor_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<style type="text/css">
  form label{
	display: inline-block;
	width:180px;
}
</style>
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register as a Tutor</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ tutor_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}

    </div>

  </div>
  <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script type="text/javascript">
      $(document).ready(function(){
          var label = $("label[for='"+$('#id_salary').attr('id')+"']");
          console.log($("input[type='checkbox']").val());
    
    $('#id_contracted').click(function() {
    if( $('#id_contracted').is(':checked')) {
        $("#id_salary").hide();
        label.hide();
    } else {
        $("#id_salary").show();
        label.show();
    }
  
}); 


});
  </script>

<style type="text/css">
    body {
      background-color: #f97925;
    }
  </style>

{% endblock %}

templates/tutor_app/review_list.html
{% extends "tutor_app/base.html" %}
{% block body_block %}
    <h2>Latest reviews</h2>
    
    {% if latest_review_list %}
    <div>
        {% for review in latest_review_list %}
        <div>
            <h4><a href="{% url 'tutor_app:review_detail' review.id %}">
            {{ review.tutor.name }}
            </a></h4>
            <h6>rated {{ review.rating }} of 5 by {{ review.user_name }}</h6>
            <p>{{ review.comment }}</p>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No reviews are available.</p>
    {% endif %}
{% endblock %}

templates/tutor_app/tutor_detail.html
{% extends 'student_app/base.html' %}
{% block body_block %}
    <h2>{{ tutor.first_name }} {{tutor.last_name}}</h2>
    
    <h3>Recent reviews</h3>
    
    {% if tutor.review_set.count > 0 %}
    <h2 style="display:inline;"><small>Average Rate: </small> {{ tutor.average_rating | floatformat }}/6 </h2> ({{ tutor.review_set.count }} reviews)
    
        {% if tutor.review_set.count > 0 %}
        <table class="table" style="margin-top: 20px;">
            <tbody>
            {% for review in tutor.review_set.all %}
            <tr><td>
                <em>{{ review.comment }}</em><br/>
                <span class="stars" style="margin-top: 15px;">{{ review.rating }}</span><small> by {{ review.user_name }}</small>
                <!--<h5><a href="{% url 'tutor_app:review_detail' review.id %}">-->
                <!--Read more-->
                <!--</a></h5>-->
            </td></tr>
            {% endfor %}
            </tbody>
        </table>
        
        {% endif %}
    {% else %}
        <p>No reviews for this tutor yet</p>    
    {% endif %}
    <script type="text/javascript">
    $.fn.stars = function() {
      return $(this).each(function() {
        // Get the value
        var val = parseFloat($(this).html());
        // Make sure that the value is in 0 - 5 range, multiply to get width
        var size = Math.max(0, (Math.min(6, val))) * 16;
        // Create stars holder
        var $span = $('<span />').width(size);
        // Replace the numerical value with stars
        $(this).html($span);
      });
    }
    $(document).ready(function() {
      $('span.stars').stars();
    });
  </script>
{% endblock %}

templates/tutor_app/tutor_list.html
{% block title %}
<h2>Top Tutors</h2>
{% endblock %}

{% block content %}
{% if tutor_list %}
<div class="row">
    {% for tutor in tutor_list %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'tutor_app:tutor_detail' tutor.id %}">
        {{ tutor.first_name }} {{ tutor.last_name }}
        </a></h4>
        <h5> reviews</h5>
        <h5>{{tutor.average_rating}} average rating</h5>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No tutors are available.</p>
{% endif %}
{% endblock %}