myTutor_app/urls.py
from django.conf.urls import url
from myTutor_app import views


app_name = 'myTutor_app'

urlpatterns=[
   url(r'^index/$',views.index,name='index'),
   url(r'^user_login/$',views.user_login,name='user_login'),
   url(r'^index/update_wallet/$',views.update_wallet,name='update_wallet'),
   url(r'^transactions/$',views.transactions,name='transactions')

]

tutoria/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from start_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^student_app/',include('student_app.urls')),
    url(r'^myTutor_app/',include('myTutor_app.urls')),
    url(r'^tutor_app/',include('tutor_app.urls')),
    url(r'^session_app/',include('session_app.urls')),
    url(r'^reset-password/$',password_reset,name='password_reset'),
    url(r'^reset-password/done/$',password_reset_done,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset-password/complete/$',password_reset_complete,name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myTutor_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class myTutor(models.Model):
    user = models.OneToOneField(User,null=True)
    wallet = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username
        
class Transaction_M(models.Model):
    mytutor = models.ForeignKey(myTutor, on_delete=models.CASCADE)
    amount = models.FloatField(null = True)
    pub_date = models.DateTimeField()
    desc = models.CharField(max_length=30,null=True)

myTutor_app/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

myTutor_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from myTutor_app.models import myTutor,Transaction_M
from myTutor_app.forms import UserForm
import json
from django.http import JsonResponse


# Create your views here.
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user =authenticate(username=username,password=password)
        

        if user:
            if user.is_active:
                login(request,user)
                return redirect('/myTutor_app/index')

            else:
                return HttpResponse('Not Registered as a Student')
        else:
            print('Someone Tried to login and failed')
            print('Username: {} and password: {}'.format(username,password))
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request,'myTutor_app/login.html',{})
 
@login_required      
def index(request):
    user_id = request.user
    my_Tutor = myTutor.objects.get(user = user_id)
    return render(request,'myTutor_app/index.html',{'mytutor':my_Tutor})
    
def update_wallet(request):
        user_id = request.user
        data = request.GET.get("value")
        print('hello')
        print(data)
        rand_json = { }
        mytutor = myTutor.objects.get(user = user_id)
        print(type(data))
        if mytutor.wallet < float(data):
            return JsonResponse({"error":"error"})
        else:
            mytutor.wallet -= float(data)
            mytutor.save()
            return JsonResponse(rand_json)
            
def transactions(request):
    transaction = Transaction_M.objects.all()
    return render(request,"myTutor_app/transactions.html",{'transactions':transaction})

    
        

templates/myTutor_app/base.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Tutoria</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/main.css"/>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <style type="text/css">
    body {
      background-color: #f97925;
    }
  </style>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          {% if user.is_authenticated %}
          <li><a class="navbar-brand" href="{% url 'myTutor_app:index' %}">Tutoria</a></li>
          {% else %}
          <li><a class="navbar-brand" href="{% url 'index' %}">Tutoria</a></li>
          {% endif %}
        </ul>

				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></a>
						<ul class="dropdown-menu">
						  <li><a  class="dropdown-item">Wallet: ${{mytutor.wallet}}</a></li>
						  <li><a  class="dropdown-item" href="{% url 'myTutor_app:transactions' %}">Transactions</a></li>
							{% if user.is_superuser %}
								<li role="separator" class="divider"></li>
								<li  class="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">Admin Panel</a></li>
							{% endif %}
							<li role="separator" class="divider"></li>
							<li><a class="dropdown-item"  href="{% url 'index' %}">Logout</a></li>
						</ul>
					</li>
					{% else %}
						
					{% endif %}
				</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

templates/myTutor_app/index.html
{% extends "myTutor_app/base.html" %}
{% block body_block %}
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
     console.log('hi');
      $(document).ready(function() {
                $('#send_val').click(function(){
                    console.log('hi');
                    if ($('#inputVal3').val() < 0) {
                      alert('enter a positive value!');
                      location.reload();
                      return;
                    }
                		let add_val = { 
                    	"value": $('#inputVal3').val()
                    };
                    console.log(add_val);
                    $.ajax({
                    type:"GET",
                    url : "update_wallet",
                    data: add_val, // do I need to pass data if im GET ting?
                    dataType: 'json',
                    success : function(new_data){
                        if(new_data.error=="error")
                      alert('not enough funds')
                      else
                      alert('successfully retrieved funds')
                      location.reload()
                    },
                    error : function() {
                    		alert('error adding value');
                    		location.reload();
                    }
                });//end ajax   
              });//end click
            });
</script>

<div class="container">
<div class ="jumbotron">
     <p>You have ${{mytutor.wallet}} in your wallet!</p>
     
      <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModalHorizontal">
                  Retrieve Funds From Wallet
            </button>
     
     
     
     
     <div class="modal fade" id="myModalHorizontal" tabindex="-1" role="dialog" 
       aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <!-- Modal Header -->
              <div class="modal-header">
                  <button type="button" class="close" 
                     data-dismiss="modal">
                         <span aria-hidden="true">&times;</span>
                         <span class="sr-only">Close</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel">
                      Retrieve Funds
                  </h4>
              </div>
              
              <!-- Modal Body -->
              <div class="modal-body">
                  
                  <form class="form-horizontal" role="form">
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="inputEmail3">Enter the Amount</label>
                      <div class="col-sm-10">
                          <input type="number" class="form-control" 
                          id="inputVal3" placeholder="In Hong Kong Dollars"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                        </div>
                      </div>
                    </div>
                  </form>
              </div>
              <!-- Modal Footer -->
              <div class="modal-footer">
                  <button type="button" class="btn btn-default"
                          data-dismiss="modal">
                              Close
                  </button>
                  <button id="send_val" type="button" class="btn btn-primary">
                      Retrieve Value
                  </button>
              </div>
          </div>
      </div>
  </div>
</div>

<style type="text/css">
  .modal-body .form-horizontal .col-sm-2,
  .modal-body .form-horizontal .col-sm-10 {
    width: 100%
  }
</style>
    
</div>

</div>
{% endblock %}

templates/myTutor_app/login.html
{% extends "myTutor_app/base.html" %}
{% block body_block %}
 <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'myTutor_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>
        <a href='/reset-password'>Forgot Password</a>

    </div>
  </div>
  
{% endblock %}

templates/myTutor_app/registration.html
{% extends "tutor_app/base.html" %}
{% block body_block %}   
        
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ student_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
{% endblock %}

templates/myTutor_app/transactions.html
{% extends 'myTutor_app/base.html' %}
{% block body_block %}
<style>
#transactions {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#transactions td, #transactions th {
    border: 2px solid #000;
    padding: 8px;
}

#transactions tr:nth-child(even){background-color: #f97925;}

#transactions tr:hover {background-color: #ddd;}

#transactions th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #f97925;
    color: white;
}
</style>
<div class="jumbotron">
    <h2> Transaction History </h2>
        <table id="transactions">
            <thead>
                <tr>
                    <th>
                        Amount
                    </th>
                    <th>
                        Date of Transaction
                    </th>
                    <th>
                        Description
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <td>
                        {{ transaction.amount }}
                    </td>
                    <td>
                        {{ transaction.pub_date }}
                    </td>
                    <td>
                        {{ transaction.desc }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>





{% endblock %}