session_app/urls.py
from django.conf.urls import url
from session_app import views

# SET THE NAMESPACE!
app_name = 'session_app'

urlpatterns=[
   url(r'^sessions/$',views.sessions,name='sessions'),
   url(r'^book_session/$',views.book_session,name='book_session'),
   url(r'^cancel_session/$',views.cancel_session,name='cancel_session'),
    
]

student_app/urls.py
from django.conf.urls import url
from student_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete


# SET THE NAMESPACE!
app_name = 'student_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^index/$',views.index,name='index'),
    url(r'^switch/$',views.switch,name='switch'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^view_tutors/$',views.view_tutors,name='view_tutors'),
   # url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^session_list/(?P<tutor_id>\w+)$', views.session_list, name='session_list'),
    url(r'^index/update_wallet', views.update_wallet, name='update_wallet'),
    url(r'^warning/$', views.warning, name='warning'),
    url(r'^transactions/$', views.transactions, name='transactions'),
    #url(r'^timeSlots/$',views.timeSlots,name='timeslots'),
    url(r'^sort_price/$', views.sort_price, name='sort_price'),
    #url(r'^sort_rating/$', views.sort_rating, name='sort_rating'),
]

tutor_app/urls.py
from django.conf.urls import url
from tutor_app import views

# SET THE NAMESPACE!
app_name = 'tutor_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^index/$',views.index,name='index'),
    url(r'^switch/$',views.switch,name='switch'),
    url(r'^profile/(?P<tutor_id>\w+)/$', views.profile, name='profile'),
    url(r'^edit/', views.edit_profile, name='edit_profile'),
    url(r'^blockSession/$',views.blockSession, name='blockSession'),
    url(r'^timeSlots/$',views.timeSlots, name='timeSlots'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^review/$', views.review_list, name='review_list'),
    url(r'^tutor/$', views.tutor_list, name='tutor_list'),
    url(r'^tutor/(?P<tutor_id>[0-9]+)/$', views.tutor_detail, name='tutor_detail'),
    url(r'^deactivate/$', views.deactivate, name='deactivate'),
    url(r'^tutor/(?P<tutor_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^transactions/$',views.transactions,name='transactions')
]

tutoria/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from start_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^student_app/',include('student_app.urls')),
    url(r'^myTutor_app/',include('myTutor_app.urls')),
    url(r'^tutor_app/',include('tutor_app.urls')),
    url(r'^session_app/',include('session_app.urls')),
    url(r'^reset-password/$',password_reset,name='password_reset'),
    url(r'^reset-password/done/$',password_reset_done,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset-password/complete/$',password_reset_complete,name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Student(models.Model):
    user = models.OneToOneField(User,null=True)

    wallet = models.FloatField(default=0)
    phone = models.CharField(max_length=30,null=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
        
class Transaction_S(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    amount = models.FloatField(null = True)
    pub_date = models.DateTimeField()
    desc = models.CharField(max_length=30,null=True)

student_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from student_app.models import Student
import django_filters
from tutor_app.models import Tutor

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')

class StudentForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ('profile_pic', 'phone')

class EditProfileForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = (
            'profile_pic', 'phone'
        )
    def __init__(self, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

class EditUserForm(UserChangeForm):
    class Meta():
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password'
        )

class TutorFilter(django_filters.FilterSet):
    class Meta():
        model = Tutor
        fields = ['first_name','last_name','subject_tag','university','courses','contracted']

student_app/views.py
from django.shortcuts import render
from student_app.forms import UserForm , StudentForm,TutorFilter
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from session_app.models import Session
from student_app.models import Student
from django.shortcuts import redirect
from django.contrib.auth.forms import UserChangeForm
from tutor_app.models import Tutor
from django.contrib.auth.models import User
from student_app.forms import EditProfileForm
from student_app.forms import EditUserForm
from django.http import JsonResponse
from datetime import datetime,timedelta
from django.contrib.messages import get_messages
import datetime
import json
import unicodedata
from tutor_app.models import Timeslot
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from student_app.models import Transaction_S

# Create your views here.
def index(request):
    storage = get_messages(request)
    print("STorage")
    for message in storage:
        print("why?")
        print(message)
    user_id=request.user
    # student_id=Student.objects.get(user=user_id)p
    # session=Session.objects.filter(student=student_id)
    # print(session)
    try:
        student_id=Student.objects.get(user=user_id)
        print(student_id)
        
    except:
        student_id= None
    if student_id != None:    
        try:
            session = Session.objects.filter(student=student_id)
            print (session)
            return render(request,'student_app/index.html',{'sessions':session})
        except Session.DoesNotExist:
            session = None
            print(session)
    return render(request,'student_app/index.html', {'messages':storage})

def switch(request):
    logout(request)
    return redirect('/tutor_app/index')

@login_required
def user_logout(request):
    logout(request)
    return render(request,'student_app/index.html')

def register(request):
    registered =False
            
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        student_form = StudentForm(data=request.POST)

        if user_form.is_valid() and student_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            student = student_form.save(commit=False)
            student.user = user

            if 'profile_pic' in request.FILES:
                student.profile_pic = request.FILES['profile_pic']

            student.save()

            registered = True

        else:
            print(user_form.errors,student_form.errors)

    else:
        user_form = UserForm()
        student_form = StudentForm()

    return render(request,'student_app/registration.html',
                            {'user_form':user_form,
                            'student_form':student_form,
                            'registered':registered}
                            )

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user =authenticate(username=username,password=password)
        try:
            student = Student.objects.get(user=user)
        except:
            student= None

        if user:
            if student != None:
                login(request,user)
                return redirect('/student_app/index')

            else:
                return HttpResponse('Not Registered as a Student')
        else:
            print('Someone Tried to login and failed')
            print('Username: {} and password: {}'.format(username,password))
            return HttpResponse('Invalid login details supplied')
    else:
        return render(request,'student_app/login.html',{})
        
@login_required
def session_list(request,tutor_id):
    tutor = Tutor.objects.get(id=tutor_id)
    student=Student.objects.get(user=request.user)
    blocked_session = Session.objects.values_list('session_time','student_id').filter(tutor = tutor).filter(status = 2).all()
    booked_session = Session.objects.values_list('session_time','student_id').filter(tutor = tutor).filter(status = 1).all()
    self_session = Session.objects.values_list('session_time','student_id').exclude(tutor = tutor).filter(status = 1).all()
    booked_list = []
    blocked_list = []
    self_booked = []
    other_self_booked=[]
    booked_day = []
    for session in blocked_session:
        blocked_list.append(session[0].strftime("%Y-%m-%dT%H:%M:%S"))
    for session in booked_session:
        booked_list.append(session[0].strftime("%Y-%m-%dT%H:%M:%S"))
        print(student.id)
        if (student.id == session[1]):
            self_booked.append(session[0].strftime("%Y-%m-%dT%H:%M:%S"))
            booked_day.append(session[0].strftime("%Y-%m-%d"))
    for session in self_session:
        if (student.id == session[1]):
            other_self_booked.append(session[0].strftime("%Y-%m-%dT%H:%M:%S"))
    preset_time = []
    time_slot = []
    time_array = []
    date_array = []
    date_list = []
    lock_slot = []
    time_range = 18
    elem_time = datetime.time(9, 00)
    time_delta = datetime.timedelta(minutes = 30)

    

    curr_date = datetime.datetime.now().date()

    date_delta = datetime.timedelta(days = 1)
    lock_time = datetime.datetime.now() + date_delta + time_delta*16
    if tutor.contracted == False:
        time_range = 9
        time_delta = datetime.timedelta(minutes = 60)
    for i in range(time_range):
        temp_time = datetime.datetime.combine(datetime.date(1, 1, 1), elem_time)
        preset_time.append(elem_time)
        time_array.append(elem_time.strftime("%H:%M:%S"))
        elem_time = (temp_time + time_delta).time()
    for i in range(7):
        temp_date = datetime.datetime.combine(curr_date, datetime.time(1,1))
        date_array.append(curr_date.strftime("%Y-%m-%d"))
        date_list.append(curr_date.strftime("%d/%m/%y (%a)"))
        curr_date = (temp_date + date_delta).date()
    for i in range(time_range):
        curr_date = datetime.datetime.now().date()
        time_slot.append(preset_time[i].strftime("%H:%M"))
        for j in range(7):
            time_to_append = datetime.datetime.combine(curr_date, preset_time[i]).isoformat()
            if datetime.datetime.combine(curr_date, preset_time[i]) <= lock_time:
                lock_slot.append(time_to_append)
            time_slot.append(time_to_append)
            temp_date = datetime.datetime.combine(curr_date, datetime.time(1,1))
            curr_date = (temp_date + date_delta).date()

    return render(request, 'student_app/session_list.html', {'tutor_id':tutor_id,'self_booked':self_booked,'other_self_booked':other_self_booked,'time_array':time_array,'date_list':date_list,'date_array':date_array, 'blocked_session_list': blocked_list,'booked_day':booked_day, 'booked_session_list': booked_list, 'lock_slot': lock_slot})
  
@login_required      
def edit_profile(request):
    args = {}
    if request.method == 'POST':
        form = EditProfileForm(request.POST, request.FILES, instance=request.user.student)
        form2 = EditUserForm(request.POST, instance=request.user)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return redirect('/student_app/index')
    
    else:
        form = EditProfileForm(instance=request.user.student)
        form2 = EditUserForm(instance=request.user)
        args['form'] = form
        args['form2'] = form2
        return render(request, 'student_app/edit_profile.html', args)
        
def view_tutors(request):
    tutor_list = Tutor.objects.filter(active = True)
    tutor_filter = TutorFilter(request.GET,queryset=tutor_list)
    return render(request, 'student_app/tutor_list.html', {'filter': tutor_filter})
    
def sort_price(request):
    tutor_list = Tutor.objects.order_by('salary')
    tutor_filter = TutorFilter(request.GET,queryset=tutor_list)
    return render(request,'student_app/tutor_list.html', {'filter':tutor_filter})
    
# def sort_rating(request):
#     tutor_list = Tutor.objects.order_by('average_rating')
#     tutor_filter = TutorFilter(request.GET,queryset=tutor_list)
#     return render(request,'student_app/tutor_list.html', {'filter':tutor_filter})
    
# def show_available(request):
#     tutor_list = Tutor.objects.all()
#     for tutor in tutor_list:
#         session = Session.objects.filter(tutor = tutor).count()
#         if session < 

    
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was changed successfully')
            return redirect('change_password')
        else:
            messages.error(request, 'ERROR > ')
        
    else: 
        form = PasswordChangeForm(request.user)
    return render(request, 'student_app/change_password.html', {
        'form': form
    })
    
def update_wallet(request):
        user_id = request.user
        data = request.GET.get("value")
        print('hello')
        print(data)
        rand_json = { }
        student_id = Student.objects.get(user = user_id)
        print(type(data))
        student_id.wallet += float(data)
        student_id.save()
        transaction = Transaction_S(student = student_id, amount = float(data), pub_date = datetime.datetime.now(), desc="Add Funds to Wallet")
        transaction.save()
        
        return JsonResponse(rand_json)

# def datetime_range(start, end, delta):
#     current = start
#     while current < end:
#         yield current
#         current += delta
            

templates/student_app/base.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Tutoria</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/main.css"/>
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <style type="text/css">
    body {
      background-color: #f97925;
    }
  </style>
  <body><br>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          {# Django Home Link / Admin Link / Register Link#}
          {% if user.is_authenticated %}
          <li><a class="navbar-brand" href="{% url 'student_app:index' %}">Tutoria</a></li>
          {% else %}
          <li><a class="navbar-brand" href="{% url 'index' %}">Tutoria</a></li>
          {% endif %}
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'student_app:view_tutors' %}">Book a session</a></li>
          {% endif %}
        </ul>

				<ul class="nav navbar-nav navbar-right">
					<li><a class="navbar-link" href="{% url 'student_app:switch' %}">Switch to Tutor</a></li>
					{% if user.is_anonymous %}
          <li><a class="navbar-link" href="{% url 'student_app:register' %}">Register</a></li>
          {% endif %}
					{% if user.is_authenticated %}
					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{user.username}} <span class="caret"></a>
						<ul class="dropdown-menu">
						  <li><a  class="dropdown-item">Wallet: ${{user.student.wallet}}</a></li>
							<li><a class="dropdown-item"  href="{% url 'student_app:edit_profile' %}">Edit Profile</a></li>
							<li><a class="dropdown-item"  href="{% url 'student_app:transactions' %}">Transaction History</a></li>
							{% if user.is_superuser %}
								<li role="separator" class="divider"></li>
								<li  class="nav-item"><a class="navbar-link" href="{% url 'admin:index' %}">Admin Panel</a></li>
							{% endif %}
							<li role="separator" class="divider"></li>
							<li><a class="dropdown-item"  href="{% url 'student_app:logout' %}">Logout</a></li>
						</ul>
					</li>
					{% else %}
						<li  class="nav-item"><a class="navbar-link" href="{% url 'student_app:user_login' %}">Login</a></li>
					{% endif %}
				</ul>
      </div>
    </nav>
    <div class="container">
      
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

templates/student_app/change_password.html
{% extends "student_app/base.html" %}

{% block body_block %}
<div class = "jumbotron">
    <h3> Change Password </h3>
    <br>
    <form method = "post">
        {% csrf_token %}
        {{ form }}
        <br>
        <br>
        <button class="btn btn-primary" type = "submit"> Change Password </button>  
    </form>
</div>
{% endblock %}

templates/student_app/edit_profile.html
{% extends "student_app/base.html" %}

{% block body_block %}
<div class="container  jumbotron">
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form2.as_p }}
        <div style="display: flex; align-items: center; justify-content: center; width: 400px; border: 2px dashed lightgray">
            <img id="preview" src="{{user.student.profile_pic.url}}" alt="No profile picture yet" style="max-width: 400px;"/>
        </div>
        {{ form.as_p }}
        <a href="{%url 'student_app:change_password' %}"  class = "btn">Change Password</a>
        <button type="submit">Submit</button>
    </form>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#preview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#id_profile_pic').change(function(){
            readURL(this);
        });
    });
</script>
{% endblock %}

templates/student_app/index.html
{% extends "student_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
        <h3>Your Sessions:</h3>
        <div>
            {% for session in sessions %}
            <p>
              {{session.course}} - {{session.tutor}} - {{session.session_time}}
            </p><a href="{% url 'session_app:cancel_session' %}?sess={{session.id}}">Cancel Session</a>
            {% empty %}
            <p>
              You have not enrolled in any tutorial session
            </p>
            {% endfor %}
          
        </div>
          
         
    {% else %}
      <h1>Welcome to Student Portal</h1>
      <h2>Please login/register to start using Tutoria</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

templates/student_app/login.html
{% extends 'student_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'student_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>
        <a href='/reset-password'>Forgot Password</a>

    </div>
  </div>
{% endblock %}

templates/student_app/registration.html
{% extends "student_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<style type="text/css">
  form label{
	display: inline-block;
	width:180px;
}
</style>
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register as a Student</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ student_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

templates/student_app/session_list.html
{% extends 'student_app/base.html' %}
{% block body_block %}

<style>
	.div_box{
		width: 12.5%;
		height: 7.5%;
		border: #ddd 1px solid;
	}
</style>

  <div class="container">
    <div class="jumbotron">
        
			<div class="div_table">
				<div class="div_thead flex">
					<div class="div_box col-0 row-0"></div>
					{% for date in date_list %}
						<div class="div_box flex flex-center {{date}} row-0">{{date}}</div>
					{% endfor %}
				</div>
				<div class="div_tbody">
					
					{% for time in time_array %}
						<div class="div_trow flex">
							<div class="div_box flex flex-center col-0 row-{{forloop.counter}}">{{time}}</div>
							{% for date in date_array %}
								<div class="div_box flex flex-center {{date}} col-{{forloop.counter}} row-{{forloop.parentloop.counter}}"><input class="btn btn-primary" type="button" id="{{date}}T{{time}}" value="Book" onclick="confirm_function();location.href='/session_app/book_session?sess={{date}}T{{time}}&tutor={{tutor_id}}'"/></div>
							{% endfor %}
						</div>
					{% endfor %}
				</div>
			</div>
    </div>
  </div>
  <script type="text/javascript">
  	{% for locked in lock_slot %}
  		$(document.getElementById('{{locked}}')).prop({'value':'Locked', 'disabled':'true'}).removeClass('btn-primary').addClass('btn-warning');
  	{% endfor %}
  	{% for booked in booked_session_list %}
  		$(document.getElementById('{{booked}}')).prop({'value':'Booked', 'disabled':'true'}).removeClass('btn-primary').addClass('btn-light');
  	{% endfor %}
  	{% for day in booked_day %}
  		$(".{{day}}").children().prop({'value':'Unavailable', 'disabled':'true'}).removeClass('btn-primary').addClass('btn-light');
  	{% endfor %}
  	{% for blocked in blocked_session_list %}
  		$(document.getElementById('{{blocked}}')).css('display','none');
  	{% endfor %}
  	{% for other in other_self_booked %}
  		$(document.getElementById('{{other}}')).prop({'value':'Timeclash', 'disabled':'true'}).removeClass('btn-primary').addClass('btn-light');
  	{% endfor %}
  	{% for session in self_booked %}
  		$(document.getElementById('{{session}}')).prop({'value':'Yours', 'disabled':'true'}).addClass('btn-success').removeClass('btn-light');
  	{% endfor %}
  	
  </script>
  
	<script type="text/javascript">
		function confirm_function() {
			confirm("Click OK to confirm")
		}
	</script>
{% endblock %}

templates/student_app/tutor_list.html
{% extends 'student_app/base.html' %}

{% load widget_tweaks %}

{% block body_block %}
  <link rel="stylesheet" href="/static/css/main.css"/>
  <script type="text/javascript">
    $.fn.stars = function() {
      return $(this).each(function() {
        // Get the value
        var val = parseFloat($(this).html());
        // Make sure that the value is in 0 - 5 range, multiply to get width
        var size = Math.max(0, (Math.min(6, val))) * 16;
        // Create stars holder
        var $span = $('<span />').width(size);
        // Replace the numerical value with stars
        $(this).html($span);
      });
    }
    $(document).ready(function() {
      $('span.stars').stars();
    });
  </script>
  <form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Filter</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.first_name.label_tag }}
          {% render_field filter.form.first_name class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.last_name.label_tag }}
          {% render_field filter.form.last_name class="form-control" %}
        </div>

         <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.subject_tag.label_tag }}
          {% render_field filter.form.subject_tag class="form-control" %}
        </div>

         <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.university.label_tag }}
          {% render_field filter.form.university class="form-control" %}
        </div>

        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.courses.label_tag }}
          {% render_field filter.form.courses class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          {{ filter.form.contracted.label_tag }}
          {% render_field filter.form.contracted class="form-control" %}
        </div>

      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Filter
      </button>
     Sort by:
          <a href="{% url 'student_app:sort_price' %}"><button type="button" class="btn btn-default">Hourly Price Range</button></a>
          <!--<a href=""><button class="btn btn-default" type="button" >Average Rating</button></a>-->
    </div>

  </form>

  <table class="table table-bordered">

    <tbody>
        {% for tutor in filter.qs %}
          <tr>
            <td>
              <a class="flex flex-between" style="text-decoration:none; padding:0 15px;" href="{% url 'tutor_app:profile' tutor_id=tutor.id %}">
                <div>
                  <p>
                    <h3>{{tutor.first_name}}</h3>
                  </p>
                  <p>{{tutor.bio}}</p>
                </div>
                <div  class="flex flex-center">
                  {% if tutor.review_set.count >= 3 %}
                    <div class="flex flex-column flex-center" style="font-size:14px;"><span class="stars">{{tutor.average_rating|floatformat}}</span>{{ tutor.average_rating | floatformat }}/6</div>
                  {% endif %}
                </div>
              </a>
            </td>
            <!-- <td>{{ session.course }}</td>
            <td>{{ session.session_time }}</td>
            <td><a href="{% url 'session_app:book_session' %}?sess={{session.id}}">Book</a></td> -->
          </tr>
        {% empty %}
          <tr>
            <td colspan="5">No data</td>
          </tr>
        {% endfor %}

    </tbody>
  </table>
{% endblock %}

templates/student_app/wallet.html
<!--{% extends "student_app/base.html" %}-->
<!--{% block body_block %}-->

<!--<h1>Wallet</h1>-->

templates/student_app/warning.html
{% extends "student_app/base.html" %}

{% block body_block %}
<style>
    .warning{
    border: red 3px solid;
    width:80%;
    margin: 0 auto;
    height: 250px;
    background-color: #f9c6c6;
}
</style>
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="flex flex-column flex-center {{ message.tags }}"{% endif %}>
                <h2 style="color: red">{{ message }}</h2>
                <div>You will be redirected within 5 seconds, <a href="javascript:history.back()"> Click here</a> if it doesn't.</div>
            </div>
        {% endfor %}
        <script type="text/javascript">
            setTimeout(function() {
                history.back() // Do something after 5 seconds
            }, 5000);
        </script>
    {% endif %}

{% endblock %}