myTutor_app/urls.py
from django.conf.urls import url
from myTutor_app import views


app_name = 'myTutor_app'

urlpatterns=[
   url(r'^index/$',views.index,name='index'),
   url(r'^user_login/$',views.user_login,name='user_login'),
   url(r'^index/update_wallet/$',views.update_wallet,name='update_wallet'),
   url(r'^transactions/$',views.transactions,name='transactions')

]

student_app/urls.py
from django.conf.urls import url
from student_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete


# SET THE NAMESPACE!
app_name = 'student_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^index/$',views.index,name='index'),
    url(r'^switch/$',views.switch,name='switch'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^view_tutors/$',views.view_tutors,name='view_tutors'),
   # url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^session_list/(?P<tutor_id>\w+)$', views.session_list, name='session_list'),
    url(r'^index/update_wallet', views.update_wallet, name='update_wallet'),
    url(r'^warning/$', views.warning, name='warning'),
    url(r'^transactions/$', views.transactions, name='transactions'),
    #url(r'^timeSlots/$',views.timeSlots,name='timeslots'),
    url(r'^sort_price/$', views.sort_price, name='sort_price'),
    #url(r'^sort_rating/$', views.sort_rating, name='sort_rating'),
]

tutor_app/urls.py
from django.conf.urls import url
from tutor_app import views

# SET THE NAMESPACE!
app_name = 'tutor_app'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^index/$',views.index,name='index'),
    url(r'^switch/$',views.switch,name='switch'),
    url(r'^profile/(?P<tutor_id>\w+)/$', views.profile, name='profile'),
    url(r'^edit/', views.edit_profile, name='edit_profile'),
    url(r'^blockSession/$',views.blockSession, name='blockSession'),
    url(r'^timeSlots/$',views.timeSlots, name='timeSlots'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^review/(?P<review_id>[0-9]+)/$', views.review_detail, name='review_detail'),
    url(r'^review/$', views.review_list, name='review_list'),
    url(r'^tutor/$', views.tutor_list, name='tutor_list'),
    url(r'^tutor/(?P<tutor_id>[0-9]+)/$', views.tutor_detail, name='tutor_detail'),
    url(r'^deactivate/$', views.deactivate, name='deactivate'),
    url(r'^tutor/(?P<tutor_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^transactions/$',views.transactions,name='transactions')
]

tutoria/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from start_app import views
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm,password_reset_complete
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^student_app/',include('student_app.urls')),
    url(r'^myTutor_app/',include('myTutor_app.urls')),
    url(r'^tutor_app/',include('tutor_app.urls')),
    url(r'^session_app/',include('session_app.urls')),
    url(r'^reset-password/$',password_reset,name='password_reset'),
    url(r'^reset-password/done/$',password_reset_done,name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset-password/complete/$',password_reset_complete,name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    

    <title>Tutoria</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"

    <!-- Custom Fonts -->
    <link href="../static/css/font-awesome/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <style>
 /*!
 * Start Bootstrap - Stylish Portfolio (https://startbootstrap.com/template-overviews/stylish-portfolio)
 * Copyright 2013-2017 Start Bootstrap
 * Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap-stylish-portfolio/blob/master/LICENSE)
 */

/* Global Styles */

html, body {
  width: 100%;
  height: 100%;
}

body {
  background-color: #f97925;
  font-family: 'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif;
}

.text-vertical-center {
  display: table-cell;
  text-align: center;
  vertical-align: middle;
}

.text-vertical-center h1 {
  font-size: 4.5em;
  font-weight: 700;
  margin: 0;
  padding: 0;
}


/* Custom Button Styles */

.btn-dark {
  color: #fff;
  border: none;
  border-radius: 0;
  background-color: rgba(0, 0, 0, .4);
  width:90px;
  margin-left:20px;
}

.btn-dark:hover, .btn-dark:focus, .btn-dark:active {
  color: #fff;
  background-color: rgba(0, 0, 0, .7);
}

.btn-light {
  color: #333;
  border: none;
  border-radius: 0;
  background-color: rgb(255, 255, 255);
}

.btn-light:hover, .btn-light:focus, .btn-light:active {
  color: #333;
  background-color: rgba(255, 255, 255, .8);
}


/* Custom Horizontal Rule */

hr.small {
  max-width: 100px;
}


/* Side Menu */

#sidebar-wrapper {
  position: fixed;
  z-index: 1000;
  right: 0;
  overflow-y: auto;
  width: 250px;
  height: 100%;
  -webkit-transition: all .4s ease 0s;
  -moz-transition: all .4s ease 0s;
  -ms-transition: all .4s ease 0s;
  -o-transition: all .4s ease 0s;
  transition: all .4s ease 0s;
  transform: translateX(250px);
  background: #222;
}

.sidebar-nav {
  position: absolute;
  top: 0;
  width: 250px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.sidebar-nav li {
  line-height: 40px;
  text-indent: 20px;
}

.sidebar-nav li a {
  display: block;
  text-decoration: none;
  color: #999;
}

.sidebar-nav li a:hover {
  text-decoration: none;
  color: #fff;
  background: rgba(255, 255, 255, .2);
}

.sidebar-nav li a:active, .sidebar-nav li a:focus {
  text-decoration: none;
}

.sidebar-nav>.sidebar-brand {
  font-size: 18px;
  line-height: 55px;
  height: 55px;
}

.sidebar-nav>.sidebar-brand a {
  color: #999;
}

.sidebar-nav>.sidebar-brand a:hover {
  color: #fff;
  background: none;
}

#menu-toggle {
  position: fixed;
  z-index: 1;
  top: 0;
  right: 0;
}

#sidebar-wrapper.active {
  right: 250px;
  width: 250px;
  -webkit-transition: all .4s ease 0s;
  -moz-transition: all .4s ease 0s;
  -ms-transition: all .4s ease 0s;
  -o-transition: all .4s ease 0s;
  transition: all .4s ease 0s;
}

.toggle {
  font-size: 1em;
  margin: 5px 5px 0 0;
  padding: 15px 20px;
}


/* Header */

.header {
  position: relative;
  display: table;
  width: 100%;
  height: 100%;
  background: url(../static/117465.jpg) no-repeat center center scroll;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}


/* About */

.about {
  padding: 50px 0;
}


/* Services */

.services {
  padding: 50px 0;
}

.service-item {
  margin-bottom: 30px;
}


/* Callout */

.callout {
  display: table;
  width: 100%;
  height: 400px;
  color: #fff;
  background: url(../img/callout.jpg) no-repeat center center scroll;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}


/* Portfolio */

.portfolio {
  padding: 50px 0;
}

.portfolio-item {
  margin-bottom: 30px;
}

.img-portfolio {
  margin: 0 auto;
}

.img-portfolio:hover {
  opacity: .8;
}


/* Call to Action */

.call-to-action {
  padding: 50px 0;
}

.call-to-action .btn {
  margin: 10px;
}


/* Map */

.map {
  height: 500px;
}

@media(max-width:768px) {
  .map {
    height: 75%;
  }
}

.map iframe {
  pointer-events: none;
}


/* Footer */

footer {
  padding: 100px 0;
}

#to-top {
  font-size: 1em;
  position: fixed;
  right: 5px;
  bottom: 5px;
  display: none;
  padding: 15px 20px;
}

</style>

  </head>

  <body>
    <!-- Navigation -->
    

    <!-- Header -->
    <header class="header" id="top">
      <div class="text-vertical-center">
        <h1>Welcome to Tutoria </h1>
        <h3>You are a:</h3>
        <br>
        <a href="{% url 'student_app:index' %}" class="btn btn-dark btn-lg">Student</a>
        <a href="{% url 'tutor_app:index' %}" class="btn btn-dark btn-lg">Tutor</a>
        <hr>
        <a href="{% url 'myTutor_app:user_login' %}">MyTutor Portal</a>
      </div>
      
    </header>
    </body>
    </html>